import type { Campaign } from '@/modules/campaigns/types';

export const MOCK_CAMPAIGNS: Campaign[] = [
  {
    id: '1',
    name: 'Early Bird Summer Sale',
    status: 'QA',
    channel: 'Email',
    priority: 'High',
    owner: { name: 'Sarah Jenkins', avatar: 'https://i.pravatar.cc/150?u=sarah' },
    dueDate: '2024-06-15',
    progress: 85,
    sla: '2h 45m',
    subject: 'Your Summer Adventure Starts Here',
    preheader: 'Get 30% off early bookings',
    cta: 'Book Now',
    segmentation: 'Global - Segment A',
    objective: 'Drive early summer conversions',
    expectedKpi: '22% Open Rate',
    squad: 'Growth',
  },
  {
    id: '2',
    name: 'Loyalty Retention Push',
    status: 'Copy',
    channel: 'Push',
    priority: 'Urgent',
    owner: { name: 'Alex Chen', avatar: 'https://i.pravatar.cc/150?u=alex' },
    dueDate: '2024-06-10',
    progress: 40,
    sla: '15m',
    objective: 'Reduce churn in pro tier',
    expectedKpi: '5% conversion',
    squad: 'Retention',
  },
  {
    id: '3',
    name: 'New Product Announcement',
    status: 'Approval',
    channel: 'WhatsApp',
    priority: 'Medium',
    owner: { name: 'Jordan Rivera', avatar: 'https://i.pravatar.cc/150?u=jordan' },
    dueDate: '2024-06-20',
    progress: 60,
    sla: '1d',
    objective: 'High visibility for alpha launch',
    expectedKpi: '90% delivery',
    squad: 'Growth',
  },
  {
    id: '4',
    name: 'Weekend Flash Sale',
    status: 'Briefing',
    channel: 'SMS',
    priority: 'High',
    owner: { name: 'Maya Patel', avatar: 'https://i.pravatar.cc/150?u=maya' },
    dueDate: '2024-06-12',
    progress: 10,
    sla: '4h',
    objective: 'Quick revenue spike',
    squad: 'Lifecycle',
  },
];
